# Generated by Django 5.0.3 on 2024-04-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komiksyweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='komiks',
            name='rok',
            field=models.PositiveSmallIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='komiks',
            name='tytul',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
