# Generated by Django 5.0.3 on 2024-04-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komiksyweb', '0002_komiks_rok_alter_komiks_tytul'),
    ]

    operations = [
        migrations.AddField(
            model_name='komiks',
            name='imdb_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='komiks',
            name='opis',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='komiks',
            name='plakat',
            field=models.ImageField(null=True, upload_to='Plakaty'),
        ),
        migrations.AddField(
            model_name='komiks',
            name='premiera',
            field=models.DateField(blank=True, null=True),
        ),
    ]
