# Generated by Django 5.0.3 on 2024-04-23 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komiksyweb', '0003_komiks_imdb_rating_komiks_opis_komiks_plakat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DodatkoweInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveSmallIntegerField(default=0)),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(4, 'Drama'), (3, 'Sci-fi'), (1, 'Horror'), (0, 'Inne'), (2, 'Komedia')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='komiks',
            name='plakat',
            field=models.ImageField(blank=True, null=True, upload_to='Plakaty'),
        ),
        migrations.AddField(
            model_name='komiks',
            name='dodatkowe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='komiksyweb.dodatkoweinfo'),
        ),
    ]
