# Generated by Django 5.0.3 on 2024-04-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komiksyweb', '0004_dodatkoweinfo_alter_komiks_plakat_komiks_dodatkowe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (2, 'Komedia'), (1, 'Horror'), (3, 'Sci-fi'), (4, 'Drama')], default=0),
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recenzja', models.TextField(blank=True, default='')),
                ('gwiazdki', models.PositiveSmallIntegerField(default=5)),
                ('komiks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komiksyweb.komiks')),
            ],
        ),
    ]
